version: '3.8'

services:
  wdijs-db:
    image: postgres:16-alpine
    container_name: wdijs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nestjs-network
  whisper:
    build:
      context: ./whisper-server
    command: python run.py
    ports:
      - '8000:8000'
    networks:
      - nestjs-network

volumes:
  postgres-data:
    driver: local

networks:
  nestjs-network:
    driver: bridge
